<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "create-your-own-content": {
        "title": "Create your own content",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2023-07-20 23:37:30",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "8506f9678f8707648747d5b8dd7f4e4c",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Set up your new site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2023-07-20 23:36:30",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "771da1f03f3a984ac61a3c7338d0219b",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Follow Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2023-07-20 23:35:30",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "25bc08ef79443dbc79590763bab83249",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "about": {
        "title": "About",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2023-07-20 23:34:30",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "5018104b5d6b648a23b0314c8db2cce5",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}